### ISSUE TITLE
Same setup with Elastic Search 5.2.2 - to check how it works in ES 5. 

### ISSUE THREAD

**Issue by maggienj** [klahnakoski/ActiveData#4]
Unit Test runs fine in Elastic Search V1.7.1 along with Python 2.7.12

Just upgraded Elastic Search to V5.2.2 

Modified the yml file and the service doesn't start with these two config lines on. 
Elasticsearch has a configuration file at config/elasticsearch.yml. You must modify it to turn on scripting. Add these two lines at the top of the file:
script.inline: on
script.indexed: on

Just removed these two lines for the sake of testing to test if the elastic service would start and it started.
Re-plugging these two lines in config/elasticsearch.yml doesn't let the service start. 

So, for now... these two lines are commented out in config/elasticsearch.yml..

( I do understand that ES5.2.2 is the latest... just wanted to see if it works fine in the latest and thats why installed the latest release )

**Comment by maggienj** [comment]
Also, it seems groovy scripting isn't supported in Version 5. 
Not sure... if ActiveData uses the groovy language in Elastic Search.

**Comment by maggienj** [comment]
If script.indexed is added then this the error message in the ES-5.2.2 log
```
[2017-03-25T11:21:08,099][INFO ][o.e.e.NodeEnvironment    ] [OX5gNnX] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-03-25T11:21:08,106][INFO ][o.e.n.Node               ] node name [OX5gNnX] derived from node ID [OX5gNnXQRtW6gThYBtxJ4w]; set [node.name] to override
[2017-03-25T11:21:08,115][INFO ][o.e.n.Node               ] version[5.2.2], pid[3484], build[f9d9b74/2017-02-24T17:26:45.835Z], OS[Windows 10/10.0/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_111/25.111-b14]
[2017-03-25T11:21:11,561][INFO ][o.e.p.PluginsService     ] [OX5gNnX] loaded module [aggs-matrix-stats]
[2017-03-25T11:21:11,562][INFO ][o.e.p.PluginsService     ] [OX5gNnX] loaded module [ingest-common]
[2017-03-25T11:21:11,563][INFO ][o.e.p.PluginsService     ] [OX5gNnX] loaded module [lang-expression]
[2017-03-25T11:21:11,563][INFO ][o.e.p.PluginsService     ] [OX5gNnX] loaded module [lang-groovy]
[2017-03-25T11:21:11,564][INFO ][o.e.p.PluginsService     ] [OX5gNnX] loaded module [lang-mustache]
[2017-03-25T11:21:11,564][INFO ][o.e.p.PluginsService     ] [OX5gNnX] loaded module [lang-painless]
[2017-03-25T11:21:11,564][INFO ][o.e.p.PluginsService     ] [OX5gNnX] loaded module [percolator]
[2017-03-25T11:21:11,564][INFO ][o.e.p.PluginsService     ] [OX5gNnX] loaded module [reindex]
[2017-03-25T11:21:11,565][INFO ][o.e.p.PluginsService     ] [OX5gNnX] loaded module [transport-netty3]
[2017-03-25T11:21:11,565][INFO ][o.e.p.PluginsService     ] [OX5gNnX] loaded module [transport-netty4]
[2017-03-25T11:21:11,567][INFO ][o.e.p.PluginsService     ] [OX5gNnX] no plugins loaded
[2017-03-25T11:21:14,520][ERROR][o.e.b.Bootstrap          ] Exception
java.lang.IllegalArgumentException: unknown setting [script.indexed] did you mean any of [script.inline, script.ingest]?
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:276) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:244) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.node.Node.<init>(Node.java:328) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) [elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) [elasticsearch-5.2.2.jar:5.2.2]
[2017-03-25T11:21:14,539][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [script.indexed] did you mean any of [script.inline, script.ingest]?
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.2.2.jar:5.2.2]
Caused by: java.lang.IllegalArgumentException: unknown setting [script.indexed] did you mean any of [script.inline, script.ingest]?
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:276) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:244) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:138) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.node.Node.<init>(Node.java:328) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.node.Node.<init>(Node.java:232) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:241) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) ~[elasticsearch-5.2.2.jar:5.2.2]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.2.2.jar:5.2.2]
	... 6 more
```

**Comment by klahnakoski** [comment]
I am unsure what language ES1.7 is using for scripting it is not pure groovy; it seems closer to Java.

The groovy language is supported in es5+
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html

Turning the scripting language on in es5+ is probably different than 1.7:
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html

**Comment by klahnakoski** [comment]
hmm, maybe groovy is diabled in es5+
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-groovy.html

**Comment by maggienj** [comment]
I see...  Still, the script.inline and script.indexed parameters aren't accepted in ES5.

**Comment by klahnakoski** [comment]
The next step is to find which scripting language we can use, probably "painless"[1].  And how to enable it [2]

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-painless.html
[2] https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-security.html

**Comment by maggienj** [comment]
This following appears to be the correct syntax script.inline and script.indexed in ES 5.2.2

```
script.engine.groovy.inline: true
script.engine.groovy.stored: true
```

config/elasticsearch.yml has been updated for the same with the above two lines and ES5.2.2 is up and appears to be running fine now.

**Comment by maggienj** [comment]
This issue could be closed now.
