### ISSUE TITLE
Err while executing - python27 active_data/app.py --settings=resources/config/simple_settings.json

### ISSUE THREAD

**Issue by maggienj** [klahnakoski/ActiveData#6]
**Commands Executed:**
 ```
198  rm -rf ActiveData
  199  git clone https://github.com/klahnakoski/ActiveData.git
  200  git checkout master
  201  cd ActiveData
  202  git checkout master

  206  python27 -m pip install -r requirements.txt
  207  export PYTHONPATH=.
  208  export PYTHONPATH=.
  209  python27 active_data/app.py --settings=resources/config/simple_settings.json

```
**Result:**

$ python27 active_data/app.py --settings=resources/config/simple_settings.json
kabalidaa - 2017-04-08 18:45:34 - Main Thread - "threads.py:499" (join) - "Main Thread" waiting on thread "log thread"
Traceback (most recent call last):
  File "active_data/app.py", line 192, in <module>
    setup()
  File "active_data/app.py", line 125, in setup
    Log.error("Serious problem with ActiveData service construction!  Shutdown!", cause=e)
  File "C:\ActiveData\pyLibrary\debugs\logs.py", line 375, in error
    raise e
pyLibrary.debugs.exceptions.Except: ERROR: Serious problem with ActiveData service construction!  Shutdown!
        File "active_data/app.py", line 125, in setup
        File "active_data/app.py", line 192, in <module>
caused by
        ERROR: Problem with call to http://localhost:9200/active_data_requests20170408_184534
{"mappings": {"request_log": {"properties": {"content_length": {"index": "not_analyzed", "type": "string"}, "http_user_agent": {"index": "not_analyzed", "type": "string"}, "from": {"index": "not_analyzed", "type": "string"}, "remote_addr": {"index": "not_analyzed", "type": "string"}, "timestamp": {"type": "double"}, "error": {"type": "object", "enabled": false, "store": "yes", "index": "no"}, "query": {"type": "object", "enabled": false, "store": "yes", "index": "no"}, "path": {"index": "not_analyzed", "type": "string"}, "data": {"index": "not_analyzed", "type": "string"}, "http_accept_encoding": {"index": "not_analyzed", "type": "string"}}, "dynamic_templates": [{"default_strings": {"match_mapping_type": "string", "mapping": {"index": "not_analyzed", "type": "string"}, "match": "*"}}], "_source": {"compress": true}}}, "settings": {"index": {"number_of_replicas": 0, "store": {"throttle": {"max_bytes_per_sec": "2mb", "type": "merge"}}, "number_of_shards": 3}}}
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 760, in post
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 635, in create_index
        File "C:\ActiveData\pyLibrary\meta.py", line 140, in wrapper
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 509, in get_or_create_index
        File "C:\ActiveData\pyLibrary\meta.py", line 144, in wrapper
        File "active_data/app.py", line 97, in setup
        File "active_data/app.py", line 192, in <module>
caused by
        ERROR: Bad Request: No handler found for uri [/active_data_requests20170408_184534] and method [POST]
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 738, in post
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 635, in create_index
        File "C:\ActiveData\pyLibrary\meta.py", line 140, in wrapper
        File "C:\ActiveData\pyLibrary\env\elasticsearch.py", line 509, in get_or_create_index
        File "C:\ActiveData\pyLibrary\meta.py", line 144, in wrapper
        File "active_data/app.py", line 97, in setup
        File "active_data/app.py", line 192, in <module>

**Comment by maggienj** [comment]
This issue has been merged with another open issue. So, closing this issue.
